# define the services for our app (mongo)

version: "2"
services:
  client:
    build: ./client                     # Build the dockerfile in the client directory
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app           # don't let the outside docker node_modules 
      - /usr/src/app/node_modules/        # mount over the installed dependencies
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/usr/src/app           # don't let the outside docker node_modules 
      - /usr/src/app/node_modules/        # mount over the installed dependencies
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
      