name: grading

on: [pull_request]

jobs:
  grade-1:
    name: registration tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: cd server && npm ci
    - run: cd server && npm run test-register
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        MONGODB_HOST: localhost
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
        CI: true

  grade-2:
    name: login tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: cd server && npm ci && npm run test-login
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        MONGODB_HOST: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
        CI: true

  grade-3:
    name: logout tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: cd server && npm ci && npm run test-logout
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        MONGODB_HOST: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
        CI: true

  grade-4:
    name: get_grid_data tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: cd server && npm ci && npm run test-get_grid_data
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        MONGODB_HOST: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
        CI: true

  grade-5:
    name: save_grid_data tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci && npm run test-save_grid_data
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-6:
    name: edit_grid_row tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci
      - run: cd server && npm run test-edit_grid_row
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: localhost
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-7:
    name: delete_grid_row tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci
      - run: cd server && npm run test-delete_grid_row
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: localhost
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-8:
    name: calorie_calculation tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci && npm run test-calorie_calculation
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-9:
    name: get_calories tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci && npm run test-get_calories
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-10:
    name: meal_generator tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci && npm run test-meal_generator
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-11:
    name: get_mealplan tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci && npm run test-get_mealplan
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true

  grade-12:
    name: get_recipe tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd server && npm ci && npm run test-get_recipe
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
          CI: true