name: Mongodb GitHub Actions

on: [pull_request]

jobs:
  test_server:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v1
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }} # get randomly assigned published port
        - run: cd server && npm ci "$env:SUPER_SECRET"
        - run: cd server && npm install "$env:SUPER_SECRET"
        - run: cd server && npm test "$env:SUPER_SECRET"