name: Mongodb GitHub Actions

on: [pull_request]

jobs:
  test_server:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v1
      - run: cd server && npm ci
      - run: cd server && npm test
        env: 
          MONGODB_HOST: localhost
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }} # get randomly assigned published port
