name: Mongodb GitHub Actions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
    test_server:
      runs-on: ubuntu-latest
      container: 
        image: node:latest
      services:
        mongodb:
          image: mongo
          ports:
            - 27017:27017
      steps:
        - uses: actions/checkout@v1
        - run: cd server && npm install -g mocha && npm test
          env:
            MONGODB_HOST: mongodb
            MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}