name: Mongodb GitHub Actions

on: [pull_request]

jobs:
  test_server:
    runs-on: ubuntu-latest

    container: 
      image: node:latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v1
      - run: cd server && npm install && npm test
        env:
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}

# Runs all steps on the VM
# The service containers will use host port binding instead of container networking so you access them via localhost rather than the service name
  vm-job:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        # will assign a random free host port
        - 27017/tcp

    steps:
    - uses: actions/checkout@v1     
    - run: npm ci
      working-directory: ./mongodb
    - run: cd server && npm install && npm test
      working-directory: ./mongodb
      env:
        # use localhost for the host here because we are running the job on the VM.
        # If we were running the job on in a container this would be mongodb
        MONGODB_HOST: localhost
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }} # get randomly assigned published port