name: code quality

on: [pull_request]

jobs:
  eslint_clean:
    name: no linter problems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: cd server && npm run test-style
        env:
          CI: true
